### ISSUE TITLE
2.0.6 - Cannot find module './product-iterable.js'

### ISSUE THREAD

**Issue by lselden** [ksxatompackages/require-anywhere#12]
version 2.0.6, windows.js line 4:
`const ProductIterable = require('./product-iterable.js')`

should be:
`const ProductIterable = require('product-iterable')`

because it's a node_module

```
Error: Cannot find module './product-iterable.js'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (C:\Users\Luke\AppData\Local\atom\app-1.16.0\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (C:\Users\Luke\AppData\Local\atom\app-1.16.0\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (C:\Users\Luke\AppData\Local\atom\app-1.16.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (C:\Users\Luke\.atom\packages\require-anywhere\windows.js:4:25)
    at Module._compile (C:\Users\Luke\AppData\Local\atom\app-1.16.0\resources\app.asar\src\native-compile-cache.js:109:30)
    at Object.value [as .js] (C:\Users\Luke\AppData\Local\atom\app-1.16.0\resources\app.asar\src\compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (C:\Users\Luke\AppData\Local\atom\app-1.16.0\resources\app.asar\src\native-compile-cache.js:50:27)
    at activate (C:\Users\Luke\.atom\packages\require-anywhere\index.js:47:17)
    at Object.activate (C:\Users\Luke\.atom\packages\require-anywhere\index.js:54:21)
    at Package.module.exports.Package.activateNow (C:\Users\Luke\AppData\Local\atom\app-1.16.0\resources\app.asar\src\package.js:218:19)
    at C:\Users\Luke\AppData\Local\atom\app-1.16.0\resources\app.asar\src\package.js:190:32
    at Package.module.exports.Package.measure (C:\Users\Luke\AppData\Local\atom\app-1.16.0\resources\app.asar\src\package.js:96:15)
    at C:\Users\Luke\AppData\Local\atom\app-1.16.0\resources\app.asar\src\package.js:183:26
    at Package.module.exports.Package.activate (C:\Users\Luke\AppData\Local\atom\app-1.16.0\resources\app.asar\src\package.js:180:34)
    at PackageManager.module.exports.PackageManager.activatePackage (C:\Users\Luke\AppData\Local\atom\app-1.16.0\resources\app.asar\src\package-manager.js:550:34)
    at C:\Users\Luke\AppData\Local\atom\app-1.16.0\resources\app.asar\src\package-manager.js:531:29
    at Config.module.exports.Config.transactAsync (C:\Users\Luke\AppData\Local\atom\app-1.16.0\resources\app.asar\src\config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (C:\Users\Luke\AppData\Local\atom\app-1.16.0\resources\app.asar\src\package-manager.js:526:19)
    at PackageManager.module.exports.PackageManager.activate (C:\Users\Luke\AppData\Local\atom\app-1.16.0\resources\app.asar\src\package-manager.js:508:46)
    at C:\Users\Luke\AppData\Local\atom\app-1.16.0\resources\app.asar\src\atom-environment.js:826:28
```

**Comment by KSXGitHub** [comment]
Thank you for report.
Can you `npm install require-anywhere@"2.0.7-beta"` and test it out?

**Comment by lselden** [comment]
I just updated via Atom UI (no apm needed) and it worked fine. You can close this issue.
